config/routes.rb
Rails.application.routes.draw do

  get 'shared_decks/', to: 'shared_decks#index'
  get 'shared_decks/:id', to: 'shared_decks#show', as: :shared_deck
  post 'shared_decks/:id/clone', to: 'shared_decks#clone', as: :clone_shared_deck

  resources :categories

  get 'player/:deck_id' => 'player#show', as: "player"

  resources :decks do
    member do
      patch :share
      patch :unshare
    end
    resources :cards
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'home#index'

end

app/controllers/shared_decks_controller.rb
class SharedDecksController < ApplicationController

  before_action :authenticate_user!, only: [:clone]

  def index
    @decks = Deck.shared
  end

  def show
    @deck = Deck.find_by_slug params[:id]
  end

  def clone
    @deck = Deck.find_by_slug params[:id]
    new_deck = @deck.clone_to_user current_user
    redirect_to deck_path(new_deck), notice: "Enjoy your new deck."
  end
end

app/views/shared_decks/index.html.erb
<h2>Shared Decks</h2>

<p>These decks have been created by users of this site and can be easily added
to your account. Choose a deck to preview its cards and copy it to your account.</p>


<% if @decks.any? %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Number of Cards</th>
        <th>Last updated</th>
      </tr>
    </thead>

    <tbody>
      <% @decks.each do |deck| %>

        <tr>
          <td data-label="Deck name"><%= link_to deck.name, shared_deck_path(deck.slug) %></td>
          <td data-label="Number of cards"><%= deck.cards.count %></td>
          <td data-label="Last updated"><%= time_ago_in_words deck.updated_at %> ago</td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% else %>

  <p>There are no decks shared.</p>
<% end %>

app/views/shared_decks/show.html.erb
<h2> <%= @deck.name %></h2>

<p>
  <%= @deck.description %>
</p>

<p>
  Deck shared <%= time_ago_in_words @deck.published_at %> ago.
</p>

<p>
  <% if user_signed_in? %>
    <%= button_to "Save to your decks", clone_shared_deck_path(@deck.slug), {class: "button primary"} %>
  <% else %>
    Sign in or create an account to clone this.
  <% end %>
</p>

<hr>


<div class="card_tiles">
  <% @deck.cards.each do |card| %>

    <div class="tile">
      <%= react_component('Card', card, {prerender: true}) %>
    </div>
  <% end %>
</div>