config/routes.rb
Rails.application.routes.draw do

  get 'shared_decks/', to: 'shared_decks#index'
  get 'shared_decks/:id', to: 'shared_decks#show', as: :shared_deck
  post 'shared_decks/:id/clone', to: 'shared_decks#clone', as: :clone_shared_deck

  resources :categories

  get 'player/:deck_id' => 'player#show', as: "player"

  resources :decks do
    member do
      patch :share
      patch :unshare
    end
    resources :cards
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'home#index'

end

app/models/deck.rb
class Deck < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_many :cards, dependent: :destroy

  validates :name, presence: true

  validates :category_id, presence: { message: "must be filled in to share"}, if: "slug.present?"
  validates :description, presence: { message: "must be filled in to share"}, if: "slug.present?"

  scope :shared, -> { where("slug IS NOT NULL")}

  def shared
    self.slug.present?
  end

  # Mare a deck as shared by populating the "slug" attribute and
  # the shared at date
  # Does not modify the database. Explicitly call Note#save to do that.
  def share
    self.slug  = SecureRandom.urlsafe_base64
    self.published_at = Time.now
  end

  # Marks a deck as unshared by removing the "slug" attribute and the shared
  # at date.
  # Does not modify the database. Explicitly call Note#save to do that.
  def unshare
    self.slug = nil
    self.published_at = nil
  end


  def clone_to_user(user)
    new_deck = self.dup
    new_deck.user = user

    # Make sure new deck is not shared.
    new_deck.unshare
    new_deck.save

    self.cards.each do |card|
      new_card = card.dup

      # paperclip won't duplicate image properly unless we are explicit.
      new_card.question_image = card.question_image
      new_card.deck = new_deck
      new_card.save
    end

    new_deck

  end

end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_deck, only: [:show, :edit, :update, :destroy, :share, :unshare]
  before_action :set_categories, only: [:new, :edit, :create, :update]

  # GET /decks
  # GET /decks.json
  def index
    @decks = current_user.decks.all
  end

  # GET /decks/1
  # GET /decks/1.json
  def show
  end

  # GET /decks/new
  def new
    @deck = Deck.new
  end

  # GET /decks/1/edit
  def edit
  end

  # POST /decks
  # POST /decks.json
  def create
    @deck = current_user.decks.new(deck_params)

    respond_to do |format|
      if @deck.save
        format.html { redirect_to @deck, notice: 'Deck was successfully created.' }
        format.json { render :show, status: :created, location: @deck }
      else
        format.html { render :new }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /decks/1
  # PATCH/PUT /decks/1.json
  def update
    respond_to do |format|
      if @deck.update(deck_params)
        format.html { redirect_to @deck, notice: 'Deck was successfully updated.' }
        format.json { render :show, status: :ok, location: @deck }
      else
        format.html { render :edit }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  def share
    @deck.share
    respond_to do |format|
      if @deck.save
        format.html { redirect_to @deck, notice: 'Deck was successfully shared.' }
        format.json { render :show, status: :ok, location: @deck }
      else
        format.html { render :edit }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  def unshare
    @deck.unshare
    respond_to do |format|
      if @deck.save
        format.html { redirect_to @deck, notice: 'Deck was successfully unshared.' }
        format.json { render :show, status: :ok, location: @deck }
      else
        format.html { render :edit }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end
  # DELETE /decks/1
  # DELETE /decks/1.json
  def destroy
    @deck.destroy
    respond_to do |format|
      format.html { redirect_to decks_url, notice: 'Deck was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deck
      @deck = current_user.decks.find(params[:id])
    end

    def set_categories
      @categories = Category.all.collect{|c| [c.name, c.id] }
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deck_params
      params.require(:deck).permit(:name, :description, :shared, :background_color, :foreground_color, :font, :font_size)
    end
end

app/views/decks/_form.html.erb
<%= form_for(@deck) do |f| %>
  <% if @deck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deck.errors.count, "error") %> prohibited this deck from being saved:</h2>

      <ul>
      <% @deck.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.select :category_id, @categories, :include_blank => true %>
  </div>

  <div class="field">
    <%= f.label :background_color %><br>
    <%= f.color_field :background_color %>
  </div>

  <div class="field">
    <%= f.label :foreground_color %><br>
    <%= f.color_field :foreground_color %>
  </div>
  <div class="field">
    <%= f.label :font %><br>
    <%= f.text_field :font %>
  </div>
  <div class="field">
    <%= f.label :font_size %><br>
    <%= f.text_field :font_size %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/decks/edit.html.erb
<h1>Editing Deck</h1>

<%= render 'form' %>

<%= link_to 'Show', @deck %> |
<%= link_to 'Back', decks_path %>

app/views/decks/index.html.erb
<h1>My Decks</h1>

<%= link_to 'New Deck', new_deck_path, {class: "button primary" } %>

<% if @decks.any? %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th> Cards</th>
        <th>Last updated</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @decks.each do |deck| %>
        <tr>
          <td data-label="Deck name"><%= link_to deck.name, deck %></td>
          <td data-label="Cards"><%= deck.cards.count %></td>
          <td data-label="Updated at"><%= time_ago_in_words deck.updated_at %> ago</td>
          <td data-label="Actions">
            <%= link_to 'Play', player_path(deck), {class: "button primary"} %>
            <%= link_to 'Edit', edit_deck_path(deck), {class: "button secondary"} %>
            <%= link_to 'Delete', deck, method: :delete, data: { confirm: "Are you sure you want to remove this deck and all #{deck.cards.count} cards?" }, class: "button tertiary" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% else %>

  <p>You don't have any decks. You should create one.</p>
<% end %>

app/views/decks/new.html.erb
<h1>New Deck</h1>

<%= render 'form' %>

<%= link_to 'Back', decks_path %>

app/views/decks/show.html.erb
<h2> <%= @deck.name %></h2>

<p>
  <%= @deck.description %>
</p>

<%= link_to 'Edit', edit_deck_path(@deck) %> |
<%= link_to 'Add card', new_deck_card_path(@deck) %> |
<%= link_to 'View', player_path(@deck) %> |

<% if @deck.shared %>
  Deck shared <%= time_ago_in_words @deck.published_at %> ago.
  <% path = (url_for controller: "shared_decks", action: "show", id: @deck.slug, only_path: false) %>
  <p>Deck shared at <%= link_to path, path, {id: "share_url"} %></p>
  <%= link_to "Unshare", unshare_deck_path(@deck), method: :patch %>
<% else %>
  <% if @deck.category  && @deck.description %>
    <%= link_to "Share", share_deck_path(@deck), method: :patch %>
  <% else %>
    <p>To share this deck, ensure it has a category and description.</p>
  <% end %>
<% end %>
<hr>


<% if @deck.cards.any? %>
  <div class="card_tiles">
    <% @deck.cards.each do |card| %>

      <div class="tile">
        <%= react_component('Card', card, {prerender: true}) %>

        <%= link_to 'Edit this card', edit_deck_card_path(@deck, card) %>
        <%= link_to 'Delete', [@deck, card], method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    <% end %>
  </div>

<% else %>
  <p>You don't have any cards in this deck. You should add one.</p>
<% end %>