config/routes.rb
Rails.application.routes.draw do

  get 'shared_decks/', to: 'shared_decks#index'
  get 'shared_decks/:id', to: 'shared_decks#show', as: :shared_deck
  post 'shared_decks/:id/clone', to: 'shared_decks#clone', as: :clone_shared_deck

  resources :categories

  get 'player/:deck_id' => 'player#show', as: "player"

  resources :decks do
    member do
      patch :share
      patch :unshare
    end
    resources :cards
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <title>Flashcards</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <div class="container">
      <header>
        <h1><%= link_to "CardFlashr", root_url %></h1>
      </header>

      <a class="menu-button button primary">Menu</a>
      <nav id="menu">
        <% if user_signed_in? %>
          <%=link_to "My Decks", decks_path, {class: "button"} %>
          <span class="account">Welcome <%= current_user.email %></span>
        <% else %>
          <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook), {class: "button"}  %>
          <%= link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter), {class: "button"} %>
        <% end %>
        <%=link_to "Shared Decks", shared_decks_path, {class: "button"} %>
        <% if user_signed_in? %>
          <%=link_to "Log out", destroy_user_session_path, method: :delete, class: "button" %>
        <% end %>
      </nav>

      <main role="main">
        <% if notice %>
          <div id="notice"><%= notice %></div>
        <% end %>

        <%= yield %>

      </main>
    </div>

  </body>
</html>